---
- hosts: all
  become: yes

  vars:
    ap_cidr: 10.100.0.1/24
    ap_ssid: nfcmusik
    ap_channel: 7
    ap_password: nfcmusik

  pre_tasks:
    - name: "Workaround for error: 'ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded"
      lineinfile:
        path: /etc/ld.so.preload
        regexp: '/usr/lib/arm-linux-gnueabihf/libarmmem.*\.so'
        state: absent
    - name: Install python-apt
      raw: apt -y update && apt install -y python-minimal python-apt python-setuptools
    - name: Install some base packages
      apt:
        name:
          - vim
        state: present
        update_cache: yes

  roles:
    - rpi-if-spi
